spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: 6379

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY:}
      base-url: ${SPRING_AI_OPENAI_BASE_URL:https://api.openai.com}
    vectorstore:
      milvus:
        client:
          host: ${SPRING_AI_VECTORSTORE_MILVUS_CLIENT_HOST:milvus}
          port: ${SPRING_AI_VECTORSTORE_MILVUS_CLIENT_PORT:19530}

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}

logging:
  level:
    com.rag: INFO
